twitter2/mysite/main/urls.py
from django.urls import URLPattern, path
from . import views

urlpatterns = [
    
    path('', views.create, name='create'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('delete_mode/<int:id>/', views.delete_mode, name='delete_mode'),
    path('add/', views.add, name='add'),
]

twitter2/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

twitter2/mysite/main/models.py
from django.db import models

# Create your models here.

from django.db import models
from django.urls import reverse

# Create your models here.

class mode(models.Model):
    name = models.CharField(max_length=255, null=True)
    def __str__(self):
        return self.name
class username(models.Model):
    username= models.CharField(max_length=255, blank=True, null=True)
    mode = models.ForeignKey(mode, on_delete=models.CASCADE, null=True)
    def __str__(self):
        return self.username

twitter2/mysite/main/forms.py
from django import forms
from .models import mode

class create(forms.ModelForm):
    class Meta:
        model = mode
        fields = '__all__'

twitter2/mysite/main/views.py
from operator import mod

from django.shortcuts import redirect, render
from django.http import JsonResponse

# Create your views here.


from django.shortcuts import render
from django.urls import is_valid_path
import tweepy
from . import config
from . import recommendation
from .models import mode, username
# Create your views here.

spacee = []
def create(response):
    if response.POST.get('add'):
        print('added')
    
    client = tweepy.Client(bearer_token=config.BEARER_TOKEN, 
    consumer_key=config.API_KEY,
    consumer_secret=config.API_SECRET,
    access_token=config.ACCESS_TOKEN,
    access_token_secret=config.ACCESS_TOKEN_SECRET)
    q = 'NFTs'
    space = spacee
  

    
    modes = mode.objects.all()
    users = username.objects.all()
    
    if response.POST.get('save'):
        
        t = response.POST.get('create')
        if t == '' or t == ' ' or t=='  ':
            return render(response, 'lists.html' , {'mods':modes, 'users':users, 'spaces':space})

        if mode.objects.filter(name=t).exists():
            
            mo = mode.objects.get(name=t)
            u = response.POST.get('usernames')
            if username.objects.filter(username=u).exists():
                return render(response, 'lists.html' , {'mods':modes, 'users':users, 'spaces':space})
            username.objects.create(username=u, mode=mo)
            mo.save()

            return render(response, 'lists.html' , {'mods':modes, 'users':users, 'spaces':space})
    

        else:
            
            mo = mode.objects.create(name=t)
            mo.save()
            u = response.POST.get('usernames')
            username.objects.create(username=u, mode=mo)

            return render(response, 'lists.html' , {'mods':modes, 'users':users, 'spaces':space, })
    if response.POST.get('search_space'):
        space.clear()
        txt = response.POST.get('new1')
        q = txt
        responses = client.search_spaces(query=q, max_results=10)
        for i in responses.data:
            id = i.id
            spaces = client.get_space(id=id, expansions='host_ids')
            for i in spaces.includes['users']:
                space.append(i['username'])
        

        return render(response, 'lists.html' , {'mods':modes, 'users':users, 'spaces':space, "q":q})


        
    
    else:
        
        
        return render(response, 'lists.html' , {'mods':modes, 'users':users, 'spaces':space, })



def delete(response, id):
    try:
        u = username.objects.get(id=id)
        u.delete()
    except:
        return redirect('create')


    return redirect('create')


def delete_mode(response, id):
    
    try:
        m = mode.objects.get(id=id)
        m.delete()
    except:
        return redirect('create')
    return redirect('create')

listname= ''
data = []
def add(request):
    print('rerun')
    try:
        if request.is_ajax():
            
            if request.GET.get('action') == 'id':
                print('rec1')
                id = int(request.GET.get('id'))
                print(id)
                data.append(id)
        if request.is_ajax():
            if request.GET.get('action') == 'name':
                print('rec')
                listname = str(request.GET.get('listname'))
                data.append(listname)
                
                mo = mode.objects.get(name=data[1])

                username.objects.create(username=spacee[data[0]], mode=mo)
                print('saved')
                mo.save()
                data.clear()
                return redirect('create')  
   
    
    except:
        print(spacee)
        print('crap')
        print(data)
        data.clear()

    return redirect('create')
        
            
    
  


    



twitter2/mysite/main/templates/lists.html
<!DOCTYPE html>
{% load static %}
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'index2.css' %}">
<link rel="stylesheet" href="{% static 'index.css' %}">

<form method="post"> 
    {% csrf_token %}
    
    <input type="text" id="create" type="text" name="create" class="search" placeholder="name of the list">
    
    <input type="text" id="create" type="text" name="usernames" class="search" placeholder="username ">
    <button id="save" type="submit" name="save" value="save" class="button-27" style="max-width:90px ; position: relative;left: 900px;""> Save </button>
    <input id="search1" type="text" name="new1" class="search">   </input> 
    <button id ='search_space' name="search_space" value="search_space" class="button-27" style="max-width:90px ;position: relative;left: 900px;"> search </button>
    
</form>
<body>


<div style="overflow: hidden; width: 60%;">
{% for i in mods %}

<div id="list" class="hid"> 
    <p style="position: relative;left:45%;">{{i}}</p>
    <a type="button" style="
    background-image: linear-gradient(#02041c, #012e5b);
    background-image: linear-gradient(#02041c, #012e5b);
    font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;
    position: relative; top: 10px; left:  0px;
    width: 70px; 
    height: 30px;
    border-radius: 30%;
    color: #fff;"
    href="{% url 'delete_mode' i.id %}" > Delete</a><br>
    
    
    {% for g in i.username_set.all %}
    <li id="items">
    <a href="http://twitter.com/{{g}}" style="color: #fff">{{g}}</a> <a href="{% url 'delete' g.id %}"> delete</a><br>
    </li>
    {%endfor%}
    
</div>
{%endfor%}
</div>

<div id="spaces_search">
    <h1> {{q}}</h1>
    
<form method="get">
<button id = 'open'name = 'open' value='apply'type="button" class="hidden" data-toggle="modal" data-target="#exampleModalCenter" style="position: relative;left:500px;" ></button>
</button><br>

</form>
<br> 


<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">
          {% for i in mods %}

            <input class="button-27" type="submit" id="{{i}}" value="{{i}}"> {{i}}</input>
            <script>

              $(document).on('click', '#{{i}}', function (e){
                e.preventDefault();
                
                $.ajax({
                  type: 'GET',
                  url: '{% url "add" %}',
                  
                  data: {
                    
                    listname: $('#{{i}}').val(),
                    
                    action: 'name'
                  },
                  success: function(json){
                    
                    console.log('good')
                    document.getElementById('open').click()
                  }
                })
              })
            </script>
          {%endfor%}

          <from>
          
          
        </h5>

      </div>
      <div class="modal-body">
       choose a list 
      </div>
      <div class="modal-footer">
        
      </div>
    </div>
  </div>
</div>


<div class="sidenav xs hid">
  <h1 style="margin-top: 20px;">ForU</h1>
  <button style="width: 80%; margin-top: 30px;" onClick="window.location.reload(true)" class="button-27"> refresh</button>

{% for i in spaces %}

<script>

  $(document).on('click', '#{{i}}', function (e){
    e.preventDefault();
    
    $.ajax({
      type: 'GET',
      url: '{% url "add" %}',
      
      data: {
        
        id: $('#{{i}}').val(),
        
        action: 'id'
      },
      success: function(json){
        document.getElementById('open').click()
        
      }
    })
  })
</script>
   <a  href="http://twitter.com/{{i}}"  style="color:#fff; font-weight: bold;"> {{i}}</a> <br><button type="button" name="add" id="{{i}}" value="{{forloop.counter0}}" class="button-27"> add </button><br>

</button>   
 {%endfor%}
</div>
</div>




<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>


</body>

twitter2/mysite/main/templates/your_list.html
<!DOCTYPE html>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button>go</button>
</form>

    

    

